# 频道同步配置
channels:
  # 음악分组
  - name: "TV조선"
    json_match: "TV CHOSUN"
    group: "음악"
    epg_match: "TV CHOSUN"
    default_id: "C01581.tving"
    backup_source: true  # 需要备用源
    backup_match: "TV Chosun (720p)"
  
  - name: "TV조선 2"
    json_match: "TV CHOSUN 2"
    group: "음악"
    epg_match: "TV CHOSUN 2"
    default_id: "C00585.tving"
    backup_source: true
    backup_match: "TV조선2"
    
  - name: "MBN"
    json_match: "MBN"
    group: "음악"
    epg_match: "MBN"
    default_id: ""
    backup_source: false
  
  - name: "MBN 플러스"
    json_match: "MBN 플러스"
    group: "음악"
    epg_match: "MBN 플러스"
    default_id: ""
    backup_source: false

  - name: "JTBC"
    json_match: "JTBC"
    group: "음악"
    epg_match: "JTBC"
    default_id: ""
    backup_source: false

  - name: "JTBC2"
    json_match: "JTBC2"
    group: "음악"
    epg_match: "JTBC2"
    default_id: "C15741.tving"
    backup_source: false

  - name: "JTBC4"
    json_match: "JTBC4"
    group: "음악"
    epg_match: "JTBC4"
    default_id: "C22041.tving"
    backup_source: false
    
  # 드라마分组
  - name: "KBS드라마"
    json_match: "KBS드라마"
    group: "드라마"
    epg_match: "KBS드라마"
    default_id: "617.lg"
    backup_source: false

  - name: "MBC드라마넷"
    json_match: "MBC드라마넷"
    group: "드라마"
    epg_match: "MBC드라마넷"
    default_id: "621.lg"
    backup_source: false
    
  - name: "tvN DRAMA"
    json_match: "tvN DRAMA"
    group: "드라마"
    epg_match: "tvN DRAMA"
    default_id: "C01143.tving"
    backup_source: false
    
  # 뉴스分组
  - name: "KBS1"
    json_match: "KBS1"
    group: "뉴스"
    epg_match: "KBS 1TV"
    default_id: "501.lg"
    backup_source: false

  - name: "KBS2"
    json_match: "KBS2"
    group: "뉴스"
    epg_match: "KBS2"
    default_id: "181.lg"
    backup_source: false

  - name: "KBS뉴스"
    json_match: "KBS뉴스"
    group: "뉴스"
    epg_match: "KBS뉴스"
    default_id: ""
    backup_source: false

  - name: "SBS"
    json_match: "SBS"
    group: "뉴스"
    epg_match: "SBS"
    default_id: "504.lg"
    backup_source: false

  - name: "SBS플러스"
    json_match: "SBS플러스"
    group: "뉴스"
    epg_match: "SBS플러스"
    default_id: "612.lg"
    backup_source: false
    
  - name: "MBC"
    json_match: "MBC"
    group: "뉴스"
    epg_match: "MBC"
    default_id: "503.lg"
    backup_source: false

  - name: "YTN"
    json_match: "YTN"
    group: "뉴스"
    epg_match: "YTN"
    default_id: "C00593.tving"
    backup_source: false

  - name: "YTN2"
    json_match: "YTN2"
    group: "뉴스"
    epg_match: "YTN2"
    default_id: "C01101.tving"
    backup_source: false

  - name: "연합뉴스TV"
    json_match: "연합뉴스TV"
    group: "뉴스"
    epg_match: "연합뉴스TV"
    default_id: "C00901.tving"
    backup_source: false

  - name: "tvN"
    json_match: "tvN"
    group: "뉴스"
    epg_match: "tvN"
    default_id: "C00551.tving"
    backup_source: false

  - name: "채널A"
    json_match: "채널A"
    group: "뉴스"
    epg_match: "채널A"
    default_id: "C01583.tving"
    backup_source: false

  - name: "채널A플러스"
    json_match: "채널A플러스"
    group: "뉴스"
    epg_match: "채널A플러스"
    default_id: "C17141.tving"
    backup_source: false
    
  # 경제分组
  - name: "SBS Biz"
    json_match: "SBS Biz"
    group: "경제"
    epg_match: "SBS Biz"
    default_id: "616.lg"
    backup_source: false




